version: '3.8'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./config/xilium.conf:/etc/apache2/sites-enabled/000-default.conf
      - .env:/var/www/html/.env
    ports:
      - "80:80"
    networks:
      - base

  db:
    image: mariadb:11.3
    restart: always
    env_file:
      - ./.env/database_pass
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/database_creation.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - base

networks:
  base:
    driver: bridge
