version: '3.1'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - base

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env/database_pass
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/database_creation.sql:/docker-entrypoint-initdb.d/xilium_base.sql
    platform: linux/amd64
    networks:
      - base

networks:
  base:
    driver: bridge
